// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        496,
				FirstName: "assumenda",
				LastName:  "impedit",
				Email:     "zJordan@Jabberbean.biz",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        419,
				FirstName: "eveniet",
				LastName:  "dolor",
				Email:     "HowardRiley@Jazzy.name",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        215,
				FirstName: "quibusdam",
				LastName:  "voluptas",
				Email:     "iEdwards@Plajo.com",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        686,
				FirstName: "voluptatem",
				LastName:  "nihil",
				Email:     "vPerez@Oozz.com",
				Visible:   true,
			},
		}
	return res, nil
}
