// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        221,
				FirstName: "modi",
				LastName:  "nostrum",
				Email:     "qui_doloremque@Ntags.biz",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        30,
				FirstName: "nobis",
				LastName:  "saepe",
				Email:     "et_voluptatem_illum@Twiyo.biz",
				Visible:   false,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        133,
				FirstName: "quaerat",
				LastName:  "pariatur",
				Email:     "BettyBurton@Photospace.com",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        555,
				FirstName: "voluptas",
				LastName:  "blanditiis",
				Email:     "eHart@Innojam.info",
				Visible:   true,
			},
		}
	return res, nil
}
